# This file was generated by GoReleaser. DO NOT EDIT.
cask "regtool" do
  version "1.3.0"

  on_macos do
    on_arm do
      sha256 "6933698b712740d70ea41589c30416458ee487c3431d0e121fa37b70951f578b"
      url "https://github.com/ZHallen122/RegTool/releases/download/v#{version}/regtool_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "24dcabf6d719da222c69a55f99af9e8ab84047c649f827bf3d3fb597d6b9ee56"
      url "https://github.com/ZHallen122/RegTool/releases/download/v#{version}/regtool_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "c070e8b76bdf0c28934a9a8ce72657880f822b5b5fb9ff8a4acf8bf5d0d2148d"
      url "https://github.com/ZHallen122/RegTool/releases/download/v#{version}/regtool_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "179d3353b6fc88fc5956eca0df1c2a4ca07a893c8ea7314996363a522c572f41"
      url "https://github.com/ZHallen122/RegTool/releases/download/v#{version}/regtool_#{version}_linux_amd64.tar.gz"
    end
  end

  name "regtool"
  desc "Switch package manager registries between regional mirrors"
  homepage "https://github.com/ZHallen122/RegTool"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "regtool"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/regtool"]
    end
  end

  # No zap stanza required
end
