# This file was generated by GoReleaser. DO NOT EDIT.
cask "regtool" do
  version "1.2.0"

  on_macos do
    on_arm do
      sha256 "502fe435e962f1e991ddb7244753ae85a1ca7556a2ce84b91a8d1647d5c2cbf0"
      url "https://github.com/ZHallen122/RegTool/releases/download/v#{version}/regtool_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "d03a78e24ac5c872632dc952a7939eba3af1170b87eee896fd4f140667c37a01"
      url "https://github.com/ZHallen122/RegTool/releases/download/v#{version}/regtool_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "db9d9b7e790e58e231a44ac1e3b3e8a8c88b4e82dc74f81a3b6244f2592970a4"
      url "https://github.com/ZHallen122/RegTool/releases/download/v#{version}/regtool_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "c5ea3396e4aef0ade02660bc01bd20870adcdcd72d1f3eae23570bbf8675d520"
      url "https://github.com/ZHallen122/RegTool/releases/download/v#{version}/regtool_#{version}_linux_amd64.tar.gz"
    end
  end

  name "regtool"
  desc "Switch package manager registries between regional mirrors"
  homepage "https://github.com/ZHallen122/RegTool"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "regtool"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/regtool"]
    end
  end

  # No zap stanza required
end
