# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Regtool < Formula
  desc "Switch package manager registries between regional mirrors"
  homepage "https://github.com/ZHallen122/RegTool"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ZHallen122/RegTool/releases/download/v1.0.0/regtool_1.0.0_darwin_amd64.tar.gz"
      sha256 "6f9f563ba8bc4021cc816c82d8a951e814d28810235786b9288c265cb984e55c"

      define_method(:install) do
        bin.install "regtool"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ZHallen122/RegTool/releases/download/v1.0.0/regtool_1.0.0_darwin_arm64.tar.gz"
      sha256 "11b7c833471317caf614a1bed520cd54609289a6d512d07b95090a73655fef38"

      define_method(:install) do
        bin.install "regtool"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ZHallen122/RegTool/releases/download/v1.0.0/regtool_1.0.0_linux_amd64.tar.gz"
      sha256 "34c71d9f5f7c03bd7f36a52779411dda94df86ff4c57ff1b22f46dfa4155ced7"
      define_method(:install) do
        bin.install "regtool"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ZHallen122/RegTool/releases/download/v1.0.0/regtool_1.0.0_linux_arm64.tar.gz"
      sha256 "8a964ebfbabff686b30d7eb12c3c9f179dc1c61b4fe793b12b9cedc842504517"
      define_method(:install) do
        bin.install "regtool"
      end
    end
  end

  test do
    system "#{bin}/regtool", "version"
  end
end
